repos:
  - hooks:
      - id: black
        args:
          - --line-length=99
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 21.4b0
  - hooks:
      - id: flake8
        args:
          - "--max-line-length=99"
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    